version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0

executors:
  packer:
    docker:
      - image: 'hashicorp/packer:light'

jobs:
  packer-build:
    executor: packer
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
      - ANSIBLE_LOCAL_TEMP: /home/circleci/.ansible/tmp
      - ANSIBLE_REMOTE_TEMP: /home/circleci/.ansible/tmp
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
             apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
             apk add --no-cache py3-pip
             apk add ansible
      - run:
          name: Packer init
          command: |
            packer init packer/
      - run:
          name: Build image with packer
          command: |
            packer build --var-file=packer/vars.packer.hcl packer/aws-ubuntu-nginx.pkr.hcl

workflows:

  build-image:
    jobs:
    - packer-build:
        context:
          - packer
        filters:
          tags:
            only: /^build$/
          branches:
            ignore: /.*/


  deploy_infrastructure:
    jobs:
    - terraform/validate:
        path: terraform/001-ec2
        checkout: true
        context: terraform
    - terraform/plan:
        path: terraform/001-ec2
        checkout: true
        context: terraform
        persist-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        path: terraform/001-ec2
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: main
        requires:
        - terraform/plan
  
  destroy_infrastructure:
    jobs:
    - terraform/destroy:
        path: terraform/001-ec2
        checkout: true
        attach-workspace: true
        context: terraform
        filters:
          tags:
            only: /^destroy$/
          branches:
            ignore: /.*/