version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
  slack:   circleci/slack@4.9.3


executors:
  packer:
    docker:
      - image: 'hashicorp/packer:light'


commands:


  notify-success:
    description: "Custom slack notification"
    steps:
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: A $CIRCLE_JOB job has succeeded"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Project:* $CIRCLE_PROJECT_REPONAME"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "value": "view_job",
                    "url": "${CIRCLE_BUILD_URL}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
  
  notify-error:
    description: "Custom slack notification"
    parameters:
      message:
        type: string
        default: ""
    steps:
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":red_circle: A $CIRCLE_JOB job has failed"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Project:* $CIRCLE_PROJECT_REPONAME"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "value": "view_job",
                    "url": "${CIRCLE_BUILD_URL}",
                    "action_id": "button-action"
                  }
                }
              ]
            }

jobs:
  packer-build:
    executor: packer
    steps:
      - checkout
      - run:
          name: Packer init
          command: |
            packer init packer/
      - run:
          name: Build image with packer
          command: |
            packer build --var-file=packer/vars.packer.hcl packer/aws-ubuntu-nginx.pkr.hcl


workflows:

  build-image:
    jobs:
    - packer-build:
        context:
          - packer
        filters:
          tags:
            only: /^build$/
          branches:
            ignore: /.*/


  deploy_infrastructure:
    jobs:
    - terraform/validate:
        path: terraform/001-ec2
        checkout: true
        context: terraform
    - terraform/plan:
        path: terraform/001-ec2
        checkout: true
        context: terraform
        persist-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        path: terraform/001-ec2
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: main
        requires:
        - terraform/plan
  
  destroy_infrastructure:
    jobs:
    - terraform/destroy:
        path: terraform/001-ec2
        checkout: true
        attach-workspace: true
        context: terraform
        filters:
          tags:
            only: /^destroy$/
          branches:
            ignore: /.*/