version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0

executors:
  packer:
    docker:
      - image: 'hashicorp/packer:light'

jobs:
  packer-build:
    executor: packer
    steps:
      - checkout
      - run:
          name: Packer init
          command: |
            cd packer && packer init
      - run:
          name: Build image with packer
          command: |
            packer build --var-file=packer/vars.packer.hcl packer/aws-ubuntu-nginx.pkr.hcl

workflows:

  build-image:
    jobs:
      - packer-build:
        filters:
            branches:
              only: /build\/.*/

  deploy_infrastructure:
    jobs:
    - terraform/validate:
        path: terraform/001-ec2
        checkout: true
        context: terraform
    - terraform/plan:
        path: terraform/001-ec2
        checkout: true
        context: terraform
        persist-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        path: terraform/001-ec2
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: main
        requires:
        - terraform/plan