version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
workflows:
  deploy_infra:
    jobs:
    - terraform/validate:
        path: terraform/001-ec2
        checkout: true
        context: terraform
    - terraform/plan:
        path: terraform/001-ec2
        checkout: true
        context: terraform
        persist-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        path: terraform/001-ec2
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: master
        requires:
        - terraform/plan